[project]
name = "my-first-python-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "<lwks324>", email = "<你的 GitHub 驗證 email>" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
my-first-python-project = "my_first_python_project:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
